# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrast',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet=b'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('list1_name', models.TextField(verbose_name='Enter name of Condition 1')),
                ('list1_text', models.TextField(verbose_name='Enter stimulus words separated by a comma')),
                ('baseline_choice', models.BooleanField(default=False, verbose_name='Compare to baseline.')),
                ('list2_name', models.TextField(verbose_name='Enter name of Condition 2')),
                ('list2_text', models.TextField(verbose_name='Enter stimulus words separated by a comma')),
                ('permutation_choice', models.BooleanField(default=False, verbose_name='Run permutation / bootstrap test (requires more waiting time).')),
                ('experiment_id', models.BigIntegerField(default=0, verbose_name='experiment if it exists')),
                ('figures_list', models.TextField(default='', verbose_name='Enter name of Condition 1')),
                ('MNIstr', models.TextField(verbose_name='model str')),
                ('subjstr', models.TextField(verbose_name='model str')),
                ('pmaps', models.TextField(verbose_name='model str')),
                ('replicated_figure', models.TextField(default='', verbose_name='replicated_image')),
                ('random_roi_file', models.TextField(default='', verbose_name='random_roi_file')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='roi name')),
                ('x', models.IntegerField(verbose_name='x')),
                ('y', models.IntegerField(verbose_name='y')),
                ('z', models.IntegerField(verbose_name='z')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates_holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', verbose_name='')),
                ('roi_image_filename', models.TextField(default='', verbose_name='')),
                ('allmasks', models.TextField(default='', verbose_name='')),
                ('contrast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulate.Contrast')),
            ],
        ),
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='experiment_name')),
                ('authors', models.TextField(verbose_name='experiment_name')),
                ('DOI', models.TextField(verbose_name='experiment_name')),
                ('title', models.TextField(verbose_name='experiment_name')),
                ('contrasts_res', models.TextField(verbose_name='model str')),
            ],
        ),
        migrations.AddField(
            model_name='coordinates',
            name='coordinates_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulate.Coordinates_holder'),
        ),
    ]
